name: Update Blog Feed

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Blog Posts
        uses: ayushthakur1812/update-readme-blog@main
        with:
          username: vtu22714
          target-file: README.md
